# Generated by Django 3.0.8 on 2020-08-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'نمایه کاربر', 'verbose_name_plural': 'نمایه کاربر'},
        ),
    ]
